### ISSUE TITLE
Remove from $globallySearchable

### ISSUE THREAD

**Issue by mateusgalasso** [binarybuilds/nova-mail-manager#3]
How do I remove this package from $globallySearchable?

**Comment by ltd300** [comment]
I have the same question. How do I remove this package from $globallySearchable?

Does anybody knows??

**Comment by srinathreddydudi** [comment]
```php
\BinaryBuilds\NovaMailManager\Resources\NovaMailResource::$globallySearchable = false;
```

Add this to the `boot` method of your `NovaServiceProvider`.

**Comment by ltd300** [comment]
Thank you budy.
 it works like a charm!!
